//rock = 1, paper 2, scissors 3
let computerChoice = Math.floor(Math.random() *3) +1; //multiplies random number between 0 and 0.99 by 3, then
// rounds it down to get a whole number between 1 and 3.
// The getComputerChoice function accesses the random number between 1 and
// 3 that is generated by the computerChoice variable. If the number is 1 the
// function sets the value to rock. If the number is 2 it sets it to paper. If it is 3 it
// sets it to scissors.
function getComputerChoice(rock, paper, scissors) {

if (computerChoice === 1) {
    return "rock" 
} else if (computerChoice === 2) {
    return "paper"
} else {
    return "scissors"
}

}

console.log(computerChoice); //delete this later

// humanChoice variable prompts user to enter rock, paper or scissors so they can play the game.
let humanChoice = prompt("To play, type your choice of rock, paper, or scissors.");
// get HumanChoice function takes human choice and converts it to a number, 1 for rock, 2 for paper
// and 3 for scissors
function getHumanChoice(rock, paper, scissors) {
  if (humanChoice === "rock") {
    return 1
  } else if (humanChoice === "paper") {
    return 2
  } else {
    return 3
  }
}

console.log(getHumanChoice("paper"));
// delete this later


